// This file has been generated by Specta. DO NOT EDIT.

export type ErrorAction = "None" | "Redirect"

export type ErrorPayload = { error_type: ErrorType; message: string; error: string; details: string; action_type: ErrorAction }

export type ErrorType = "Expected" | "User" | "Internal"

export type IpcUser = { full_name: string; email: string }

export type TauRpcAuthProcedureInputTypes = { proc_name: "signUp"; input_type: [string, string, string] } | { proc_name: "login"; input_type: [string, string] } | { proc_name: "getSession"; input_type: null } | { proc_name: "logout"; input_type: null }

export type TauRpcAuthProcedureOutputTypes = { proc_name: "signUp"; output_type: IpcUser } | { proc_name: "login"; output_type: IpcUser } | { proc_name: "getSession"; output_type: IpcUser } | { proc_name: "logout"; output_type: null }

const ARGS_MAP = {'auth':'{"signUp":["full_name","email","password"],"logout":[],"login":["email","password"],"getSession":[]}'}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'auth': [TauRpcAuthProcedureInputTypes, TauRpcAuthProcedureOutputTypes],
}